### ISSUE TITLE
Errors on SKR GTR when creating 9 extruders with E0 ping (link to firmware posted)

### ISSUE THREAD

**Issue by everything-tech-related** [technik-gegg/OctoPrint-Smuff#2]
https://drive.google.com/file/d/1sXf9k1aO7rJazW1mNPq70GbBhNyPGzaw/view?usp=sharing

**Comment by technik-gegg** [comment]
What do you want me to do with the firmware?

**Comment by everything-tech-related** [comment]
> What do you want me to do with the firmware?

Maybe have a look at it and see what im doing wrong or Send me a copy of yours so i can compare


I added 9 extruders with E0 pins and all the settings...SINGLENOZZLE etc
But getting errors after errors after adding extra extruders...Im also using 3x Z bed so that makes it a bit more complicated for me lol

**Comment by technik-gegg** [comment]
Sorry, no.
I'm not going to configure your Marlin. That's your job!

Also, be aware that Marlin supports a max. of 8 extruders.

**Comment by everything-tech-related** [comment]
> Sorry, no.
> I'm not going to configure your Marlin. That's your job!
> 
> Also, be aware that Marlin supports a max. of 8 extruders.

Fair enough, you willing to share yours?

Im aware of the 5 extruders. But im trying to extend that to 9 since i already have servo variant with 9 tools. Reducing to 5 would be a last resort

**Comment by technik-gegg** [comment]
I've shared mine already in the plugin README. I didn't do anything more in Marlin as you see there.

I wasn't saying 5 extruders, I said **8** extruders. Read the comment in Marlin above the #define EXTRUDERS x

**Comment by everything-tech-related** [comment]
> I've shared mine already in the plugin README. I didn't do anything more in Marlin as you see there.
> 
> I wasn't saying 5 extruders, I said **8** extruders. Read the comment in Marlin above the #define EXTRUDERS x
(Palm on Face) It compiled with 8 extruders. sorry for wasting you time. Also when you releasing stl for v5
