### ISSUE TITLE
Smuff doesn't let Otoprint work

### ISSUE THREAD

**Issue by luismello** [technik-gegg/OctoPrint-Smuff#3]
Hi TG

2020-11-11 20:46:25,159 - octoprint.plugin - ERROR - Error while calling plugin SMuFF
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_SMuFF/__init__.py", line 113, in on_event
    close_SMuFF_serial()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_SMuFF/__init__.py", line 592, in close_SMuFF_serial
    if not __sreader__ == None:
NameError: name '__sreader__' is not defined
2020-11-11 20:46:25,160 - octoprint.events - INFO - Event loop shut down
2020-11-11 20:46:25,175 - octoprint.plugin - ERROR - Error while calling plugin SMuFF
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_SMuFF/__init__.py", line 88, in on_shutdown
    close_SMuFF_serial()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_SMuFF/__init__.py", line 592, in close_SMuFF_serial
    if not __sreader__ == None:
NameError: name '__sreader__' is not defined
2020-11-11 20:46:25,212 - octoprint.server - INFO - Goodbye!

**Comment by technik-gegg** [comment]
I'll have a look at this.
Do you recall what was the last thing you did in OctoPrint before the message appeared?

**Comment by luismello** [comment]
I installed Smuff's PLugin, reset the raspberry and Octoprint didn't work anymore.

I installed other plugins as well, but these are no problem.

**Comment by technik-gegg** [comment]
It's not very likely that OctoPrint stops working because of a plugin failed initializing... 
This error message might occur if the SMuFF plugin hasn't been initialized before a shutting down OctoPrint. Under normal conditions this shouldn't happen.

What OctoPrint version are you using?

**Comment by luismello** [comment]
Hi TG

I have this msg.

OctoPrint version : unknown
OctoPi version    : 0.17.0

Octoprint crash?


The OctoPrint server is currently not running

If you just started up your Raspberry Pi, please wait a couple of seconds, then try to refresh this page.

If the issue persists, please log into your Raspberry Pi via SSH and check the following:

    Verify that the process is running: ps -ef | grep -i octoprint | grep -i python should show a python process:

    pi@octopi:~ $ ps -ef | grep -i octoprint | grep -i python
    pi 1441 1 6 11:12 ? 00:00:15 /home/pi/oprint/bin/python
    /home/pi/oprint/bin/octoprint --host=127.0.0.1 --port=5000

    If it isn't, the question is why. Take a look into ~/.octoprint/logs/octoprint.log, there might be an error logged in there that helps to determine what's wrong.
    You might also want to try if you can restart the server (if no obvious error is visible): sudo service octoprint restart.

If all that doesn't help to trouble shoot the issue, you can seek support on the OctoPrint Community Forum. Please provide your OctoPi and OctoPrint versions as well as your octoprint.log and explain what you already tried and observed as detailed as possible.

**Comment by luismello** [comment]
Hi TG

the problem happens when I upgrade to python3, I am trying to find a solution.

**Comment by luismello** [comment]
Hi TG

I reinstall OCtoprint, update python3, install Smuff and Octoprint dont start.

I use https://get.octoprint.org/py3/upgrade.py to update Octoprint to python3

**Comment by technik-gegg** [comment]
Let's try this: Setup OctoPrint with PY3 without any plugin, let ist start up and copy the logfile as it's running.
The install the SMuFF plugin and restart OctoPrint, then save the logfile again and send me both via email.

**Comment by luismello** [comment]
Hi TG

My problem was the bad Sdcard.

**Comment by technik-gegg** [comment]
Ah ok. Good to know.
